# Autogenerated by nbdev

d = { 'settings': { 'branch': 'dev',
                'doc_baseurl': '/scratch-space-for-play-explore',
                'doc_host': 'https://Korolen.github.io',
                'git_url': 'https://github.com/Korolen/scratch-space-for-play-explore',
                'lib_path': 'scratch_space_for_play_explore'},
  'syms': { 'scratch_space_for_play_explore.core': { 'scratch_space_for_play_explore.core.foo': ( 'core.html#foo',
                                                                                                  'scratch_space_for_play_explore/core.py')}}}