# Autogenerated by nbdev

d = { 'settings': { 'branch': 'dev',
                'doc_baseurl': '/scratch-space-for-play-explore',
                'doc_host': 'https://Korolen.github.io',
                'git_url': 'https://github.com/Korolen/scratch-space-for-play-explore',
                'lib_path': 'nbdev_end_to_end_tutorial'},
  'syms': { 'nbdev_end_to_end_tutorial.core': { 'nbdev_end_to_end_tutorial.core.foo': ( 'core.html#foo',
                                                                                                  'nbdev_end_to_end_tutorial/core.py')}}}